### ISSUE TITLE
Rhino: Progaurd error when using Couchbase mobile enterprise edition.

### ISSUE THREAD

**Issue by NitzDKoder** [couchbase/couchbase-lite-java-javascript#13]
Hi folks,
Using http://www.couchbase.com/dl/releases/couchbase-lite/android/1.1.0/couchbase-lite-1.1.0-android_enterprise.zip

in our project..
While applying progaurd..

```
-keep public class org.apache.cordova.** 
-keep class org.** { *; }
-keep class com.sun.** {*;}

-dontwarn com.sun.mail.imap.protocol.**
-dontwarn android.webkit.*
-dontwarn org.apache.**
-dontwarn android.support.**
-dontwarn javax.jdo.**
-dontwarn com.google.api.client.googleapis.extensions.android.gms.**
-dontwarn com.fasterxml.jackson.databind.**
-dontwarn org.mozilla.javascript.xml.impl.**


-keep class com.fasterxml.jackson.** { *; }
-keep class org.mozilla.javascript.xml.** { *; }

# rhino (javascript)
-dontwarn org.mozilla.javascript.**
-dontwarn org.mozilla.classfile.**
-keep class org.mozilla.classfile.** { *; }
-keep class org.mozilla.javascript.* { *; }
-keep class org.mozilla.javascript.tools.debugger.SwingGui.* { *; }
-keep class org.mozilla.javascript.tools.debugger.** { *; }
-keep class org.mozilla.javascript.tools.debugger.FileWindow.* { *; }
-keep class org.mozilla.javascript.tools.debugger.** { *; }
-keep class org.mozilla.javascript.tools.** { *; }
-keep class org.mozilla.javascript.annotations.** { *; }
-keep class org.mozilla.javascript.ast.** { *; }
-keep class org.mozilla.javascript.commonjs.module.** { *; }
-keep class org.mozilla.javascript.commonjs.module.provider.** { *; }
-keep class org.mozilla.javascript.debug.** { *; }
-keep class org.mozilla.javascript.jdk13.** { *; }
-keep class org.mozilla.javascript.jdk15.** { *; }
-keep class org.mozilla.javascript.json.** { *; }
-keep class org.mozilla.javascript.optimizer.** { *; }
-keep class org.mozilla.javascript.regexp.** { *; }
-keep class org.mozilla.javascript.serialize.** { *; }
-keep class org.mozilla.javascript.typedarrays.** { *; }
-keep class org.mozilla.javascript.v8dtoa.** { *; }
-keep class org.mozilla.javascript.xml.** { *; }
-keep class org.mozilla.javascript.xmlimpl.** { *; }

-keep class org.apache.http.** { *; }
-keep class org.apache.commons.codec.** { *; }
-keep class org.apache.commons.logging.** { *; }
-keep class android.net.compatibility.** { *; }
-keep class android.net.http.** { *; }
-dontwarn org.apache.http.**
-dontwarn android.webkit.**
```

```
[2016-01-13 18:31:12 - BRANCH] Note: there were 4084 duplicate class definitions.
[2016-01-13 18:31:12 - BRANCH]       You should check if you need to specify additional program jars.
[2016-01-13 18:31:12 - BRANCH] Unexpected error while performing partial evaluation:
[2016-01-13 18:31:12 - BRANCH]   Class       = [org/mozilla/javascript/tools/debugger/SwingGui]
[2016-01-13 18:31:12 - BRANCH]   Method      = [showStopLine(Lorg/mozilla/javascript/tools/debugger/Dim$StackFrame;)V]
[2016-01-13 18:31:12 - BRANCH]   Exception   = [java.lang.IllegalArgumentException] (Can't find any super classes of [org/mozilla/javascript/tools/debugger/FileWindow] (not even immediate super class [javax/swing/JInternalFrame]))
[2016-01-13 18:31:12 - BRANCH] java.lang.IllegalArgumentException: Can't find any super classes of [org/mozilla/javascript/tools/debugger/FileWindow] (not even immediate super class [javax/swing/JInternalFrame])
[2016-01-13 18:31:12 - BRANCH] at proguard.evaluation.value.ReferenceValue.generalize(ReferenceValue.java:299)
[2016-01-13 18:31:12 - BRANCH] at proguard.evaluation.value.IdentifiedReferenceValue.generalize(IdentifiedReferenceValue.java:65)
[2016-01-13 18:31:12 - BRANCH] at proguard.evaluation.value.ReferenceValue.generalize(ReferenceValue.java:481)
[2016-01-13 18:31:12 - BRANCH] at proguard.evaluation.Variables.generalize(Variables.java:136)
[2016-01-13 18:31:12 - BRANCH] at proguard.evaluation.TracedVariables.generalize(TracedVariables.java:118)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.evaluation.PartialEvaluator.evaluateSingleInstructionBlock(PartialEvaluator.java:682)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.evaluation.PartialEvaluator.evaluateInstructionBlock(PartialEvaluator.java:602)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.evaluation.PartialEvaluator.evaluateInstructionBlockAndExceptionHandlers(PartialEvaluator.java:560)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute0(PartialEvaluator.java:264)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.evaluation.PartialEvaluator.visitCodeAttribute(PartialEvaluator.java:181)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.attribute.CodeAttribute.accept(CodeAttribute.java:101)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.ProgramMethod.attributesAccept(ProgramMethod.java:79)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.attribute.visitor.AllAttributeVisitor.visitProgramMember(AllAttributeVisitor.java:95)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.util.SimplifiedVisitor.visitProgramMethod(SimplifiedVisitor.java:91)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.ProgramMethod.accept(ProgramMethod.java:71)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.ProgramClass.methodsAccept(ProgramClass.java:504)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.visitor.AllMethodVisitor.visitProgramClass(AllMethodVisitor.java:47)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.ProgramClass.accept(ProgramClass.java:346)
[2016-01-13 18:31:12 - BRANCH] at proguard.classfile.ClassPool.classesAccept(ClassPool.java:116)
[2016-01-13 18:31:12 - BRANCH] at proguard.optimize.Optimizer.execute(Optimizer.java:372)
[2016-01-13 18:31:12 - BRANCH] at proguard.ProGuard.optimize(ProGuard.java:306)
[2016-01-13 18:31:12 - BRANCH] at proguard.ProGuard.execute(ProGuard.java:115)
[2016-01-13 18:31:12 - BRANCH] at proguard.ProGuard.main(ProGuard.java:492)

```
"javax.swing.JComponent used by org/mozilla/javascript/tools/debugger/SwingGui" is not apart of android stock package..

Need to remove javax module and build a rhino?

Thanks
Nithin

**Comment by hideki** [comment]
Hi @NitzDKoder,
Does your project use couchbase-lite-java-javascript which  is for writing map/reduce function by JavaScript instead of Java?
If not, you don't need to includes Rhino too.
Thanks!

**Comment by NitzDKoder** [comment]
@hideki we use couchbase-lite-java-javascript and writing map/reduce function by JavaScript
https://github.com/jchris/coax
Anyone had this issue before?

**Comment by NitzDKoder** [comment]
@hideki 
below was 1) Download latest rhino release https://github.com/mozilla/rhino/releases/tag/Rhino1_7_7_RELEASE             
2)delete the org.mozilla.javascript.tools package from the source files using gradle. Hence sloves the below.
•	javax.swing.JComponent
is not part of android stock..( java.lang.IllegalArgumentException: Can't find any super classes of [org/mozilla/javascript/tools/debugger/FileWindow


https://github.com/mozilla/rhino/blob/master/build.gradle


sourceSets {
	    main {
	        java {
	            srcDirs 'src', 'toolsrc', 'xmlimplsrc'
	        }
	        resources {
	            srcDirs 'src', 'toolsrc'
	            exclude "build.xml"
	            exclude "manifest"
	        }
	    }

3) org.mozilla.javascript.tools is not used in couchbase-lite-java-javascript.jar.

**Comment by hideki** [comment]
Thank you for your update. It seems you could solve the problem by yourself. I will close this ticket.
